import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Clock3, MapPin, Route as RouteIcon } from "lucide-react";
import { BookingForm } from "@/components/BookingForm";
import type { TaxiPageBlock } from "@/lib/page-content";
import { PHONE, PHONE_TEL } from "@/lib/site-data";

export function TaxiPageBlocks({ blocks, preview = false }: { blocks: TaxiPageBlock[]; preview?: boolean }) {
  return <div className={preview ? "pointer-events-none" : undefined}>{blocks.map((block, index) => <TaxiPageBlockView key={block.id} block={block} index={index} />)}</div>;
}

function TaxiPageBlockView({ block, index }: { block: TaxiPageBlock; index: number }) {
  if (block.type === "benefits") return <section className="border-y border-border/60 bg-surface/30 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><Heading block={block}/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{block.items?.map((item, itemIndex) => <article key={`${block.id}-${itemIndex}`} className="rounded-md border border-border bg-background p-5"><Check className="h-5 w-5 text-gold"/><h3 className="mt-3 font-display text-lg">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.description}</p></article>)}</div></div></section>;
  if (block.type === "route") return <section className="py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><Heading block={block}/><div className="mt-8 grid gap-4 md:grid-cols-3">{[[MapPin,"Pickup",block.origin],[RouteIcon,"Destination",block.destination],[Clock3,"Travel estimate",[block.duration,block.distance].filter(Boolean).join(" · ")]].map(([Icon,label,value]) => { const IconComponent = Icon as typeof MapPin; return <div key={label as string} className="rounded-md border border-border bg-surface/40 p-5"><IconComponent className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-widest text-muted-foreground">{label as string}</p><p className="mt-1 font-display text-lg">{value as string}</p></div>; })}</div></div></section>;
  if (block.type === "imageText") return <section className="py-14"><div className={`mx-auto grid max-w-6xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8 ${block.imagePosition === "right" ? "lg:[&>div:first-child]:order-2" : ""}`}><div className="aspect-[4/3] overflow-hidden rounded-md border border-border bg-surface">{block.image && <img src={block.image} alt={block.title ?? "Taxi service"} className="h-full w-full object-cover"/>}</div><div><Heading block={block}/><Body text={block.body}/></div></div></section>;
  if (block.type === "faq") return <section className="border-y border-border/60 bg-surface/30 py-14"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><Heading block={block}/><div className="mt-8 divide-y divide-border rounded-md border border-border bg-background px-5">{block.items?.map((item, itemIndex) => <details key={`${block.id}-${itemIndex}`} className="group py-4"><summary className="cursor-pointer list-none font-display text-lg">{item.title}</summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{item.description}</p></details>)}</div></div></section>;
  if (block.type === "cta") return <section className="py-14"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><div className="rounded-md border border-gold/30 bg-surface/50 p-8 text-center shadow-gold"><Heading block={block}/>{block.buttonUrl?.startsWith("/") ? <Link to={block.buttonUrl} className="gradient-gold mt-6 inline-flex items-center gap-2 rounded-md px-6 py-3 text-sm font-semibold text-primary-foreground">{block.buttonLabel || "Book now"}<ArrowRight className="h-4 w-4"/></Link> : <a href={block.buttonUrl || `tel:${PHONE_TEL}`} className="gradient-gold mt-6 inline-flex items-center gap-2 rounded-md px-6 py-3 text-sm font-semibold text-primary-foreground">{block.buttonLabel || PHONE}<ArrowRight className="h-4 w-4"/></a>}</div></div></section>;
  if (block.type === "booking") return <section className="border-y border-border/60 bg-surface/30 py-14"><div className="mx-auto grid max-w-6xl items-start gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_1.1fr] lg:px-8"><div><Heading block={block}/><Body text={block.body || "Reserve a private, fixed-rate ride. Your trip details are sent directly to our team."}/></div><BookingForm/></div></section>;
  return <section className={index % 2 ? "border-y border-border/60 bg-surface/30 py-14" : "py-14"}><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><Heading block={block}/><Body text={block.body}/>{block.type === "service" && block.items && <div className="mt-8 grid gap-4 sm:grid-cols-2">{block.items.map((item, itemIndex) => <article key={`${block.id}-${itemIndex}`} className="rounded-md border border-border bg-background p-5"><h3 className="font-display text-lg text-gold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.description}</p></article>)}</div>}</div></section>;
}

function Heading({ block }: { block: TaxiPageBlock }) { return <>{block.eyebrow && <p className="text-xs uppercase tracking-[0.3em] text-gold">{block.eyebrow}</p>}{block.title && <h2 className="mt-3 font-display text-3xl sm:text-4xl">{block.title}</h2>}{block.description && <p className="mt-3 max-w-3xl text-muted-foreground">{block.description}</p>}</>; }
function Body({ text }: { text?: string }) { if (!text) return null; return <div className="mt-6 space-y-4 text-muted-foreground">{text.split(/\n\s*\n/).filter(Boolean).map((paragraph, index) => <p key={index} className="leading-7">{paragraph}</p>)}</div>; }