/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SkiResortRouteImport } from './routes/ski-resort'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LongDistanceRouteImport } from './routes/long-distance'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as BookOnlineRouteImport } from './routes/book-online'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BestBurlingtonTaxiToMonteral247RouteImport } from './routes/best-burlington-taxi-to-monteral-24-7'
import { Route as BestBurlingtonTaxiServiceRouteImport } from './routes/best-burlington-taxi-service'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AirportsWeServeRouteImport } from './routes/airports-we-serve'
import { Route as AirportTransfersRouteImport } from './routes/airport-transfers'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSendBookingRouteImport } from './routes/api/public/send-booking'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkiResortRoute = SkiResortRouteImport.update({
  id: '/ski-resort',
  path: '/ski-resort',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LongDistanceRoute = LongDistanceRouteImport.update({
  id: '/long-distance',
  path: '/long-distance',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOnlineRoute = BookOnlineRouteImport.update({
  id: '/book-online',
  path: '/book-online',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BestBurlingtonTaxiToMonteral247Route =
  BestBurlingtonTaxiToMonteral247RouteImport.update({
    id: '/best-burlington-taxi-to-monteral-24-7',
    path: '/best-burlington-taxi-to-monteral-24-7',
    getParentRoute: () => rootRouteImport,
  } as any)
const BestBurlingtonTaxiServiceRoute =
  BestBurlingtonTaxiServiceRouteImport.update({
    id: '/best-burlington-taxi-service',
    path: '/best-burlington-taxi-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsWeServeRoute = AirportsWeServeRouteImport.update({
  id: '/airports-we-serve',
  path: '/airports-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransfersRoute = AirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSendBookingRoute = ApiPublicSendBookingRouteImport.update({
  id: '/api/public/send-booking',
  path: '/api/public/send-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/auth': typeof AuthRoute
  '/best-burlington-taxi-service': typeof BestBurlingtonTaxiServiceRoute
  '/best-burlington-taxi-to-monteral-24-7': typeof BestBurlingtonTaxiToMonteral247Route
  '/blog': typeof BlogRouteWithChildren
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/auth': typeof AuthRoute
  '/best-burlington-taxi-service': typeof BestBurlingtonTaxiServiceRoute
  '/best-burlington-taxi-to-monteral-24-7': typeof BestBurlingtonTaxiToMonteral247Route
  '/blog': typeof BlogRouteWithChildren
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/auth': typeof AuthRoute
  '/best-burlington-taxi-service': typeof BestBurlingtonTaxiServiceRoute
  '/best-burlington-taxi-to-monteral-24-7': typeof BestBurlingtonTaxiToMonteral247Route
  '/blog': typeof BlogRouteWithChildren
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/auth'
    | '/best-burlington-taxi-service'
    | '/best-burlington-taxi-to-monteral-24-7'
    | '/blog'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/admin/blog'
    | '/admin/messages'
    | '/admin/pages'
    | '/api/public/send-booking'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/auth'
    | '/best-burlington-taxi-service'
    | '/best-burlington-taxi-to-monteral-24-7'
    | '/blog'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/blog/$slug'
    | '/admin/blog'
    | '/admin/messages'
    | '/admin/pages'
    | '/api/public/send-booking'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/auth'
    | '/best-burlington-taxi-service'
    | '/best-burlington-taxi-to-monteral-24-7'
    | '/blog'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/pages'
    | '/api/public/send-booking'
    | '/_authenticated/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AirportTransfersRoute: typeof AirportTransfersRoute
  AirportsWeServeRoute: typeof AirportsWeServeRoute
  AuthRoute: typeof AuthRoute
  BestBurlingtonTaxiServiceRoute: typeof BestBurlingtonTaxiServiceRoute
  BestBurlingtonTaxiToMonteral247Route: typeof BestBurlingtonTaxiToMonteral247Route
  BlogRoute: typeof BlogRouteWithChildren
  BookOnlineRoute: typeof BookOnlineRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  LongDistanceRoute: typeof LongDistanceRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkiResortRoute: typeof SkiResortRoute
  TermsRoute: typeof TermsRoute
  ApiPublicSendBookingRoute: typeof ApiPublicSendBookingRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ski-resort': {
      id: '/ski-resort'
      path: '/ski-resort'
      fullPath: '/ski-resort'
      preLoaderRoute: typeof SkiResortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-distance': {
      id: '/long-distance'
      path: '/long-distance'
      fullPath: '/long-distance'
      preLoaderRoute: typeof LongDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-online': {
      id: '/book-online'
      path: '/book-online'
      fullPath: '/book-online'
      preLoaderRoute: typeof BookOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-burlington-taxi-to-monteral-24-7': {
      id: '/best-burlington-taxi-to-monteral-24-7'
      path: '/best-burlington-taxi-to-monteral-24-7'
      fullPath: '/best-burlington-taxi-to-monteral-24-7'
      preLoaderRoute: typeof BestBurlingtonTaxiToMonteral247RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-burlington-taxi-service': {
      id: '/best-burlington-taxi-service'
      path: '/best-burlington-taxi-service'
      fullPath: '/best-burlington-taxi-service'
      preLoaderRoute: typeof BestBurlingtonTaxiServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports-we-serve': {
      id: '/airports-we-serve'
      path: '/airports-we-serve'
      fullPath: '/airports-we-serve'
      preLoaderRoute: typeof AirportsWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfers': {
      id: '/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof AirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/send-booking': {
      id: '/api/public/send-booking'
      path: '/api/public/send-booking'
      fullPath: '/api/public/send-booking'
      preLoaderRoute: typeof ApiPublicSendBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AirportTransfersRoute: AirportTransfersRoute,
  AirportsWeServeRoute: AirportsWeServeRoute,
  AuthRoute: AuthRoute,
  BestBurlingtonTaxiServiceRoute: BestBurlingtonTaxiServiceRoute,
  BestBurlingtonTaxiToMonteral247Route: BestBurlingtonTaxiToMonteral247Route,
  BlogRoute: BlogRouteWithChildren,
  BookOnlineRoute: BookOnlineRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  LongDistanceRoute: LongDistanceRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkiResortRoute: SkiResortRoute,
  TermsRoute: TermsRoute,
  ApiPublicSendBookingRoute: ApiPublicSendBookingRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
