/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SkiResortRouteImport } from './routes/ski-resort'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LongDistanceRouteImport } from './routes/long-distance'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as BookOnlineRouteImport } from './routes/book-online'
import { Route as AirportsWeServeRouteImport } from './routes/airports-we-serve'
import { Route as AirportTransfersRouteImport } from './routes/airport-transfers'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendBookingRouteImport } from './routes/api/public/send-booking'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkiResortRoute = SkiResortRouteImport.update({
  id: '/ski-resort',
  path: '/ski-resort',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LongDistanceRoute = LongDistanceRouteImport.update({
  id: '/long-distance',
  path: '/long-distance',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOnlineRoute = BookOnlineRouteImport.update({
  id: '/book-online',
  path: '/book-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsWeServeRoute = AirportsWeServeRouteImport.update({
  id: '/airports-we-serve',
  path: '/airports-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransfersRoute = AirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendBookingRoute = ApiPublicSendBookingRouteImport.update({
  id: '/api/public/send-booking',
  path: '/api/public/send-booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/airports-we-serve': typeof AirportsWeServeRoute
  '/book-online': typeof BookOnlineRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/long-distance': typeof LongDistanceRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ski-resort': typeof SkiResortRoute
  '/terms': typeof TermsRoute
  '/api/public/send-booking': typeof ApiPublicSendBookingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/api/public/send-booking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/api/public/send-booking'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/airport-transfers'
    | '/airports-we-serve'
    | '/book-online'
    | '/booking-confirmed'
    | '/contact'
    | '/corporate'
    | '/long-distance'
    | '/privacy'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/ski-resort'
    | '/terms'
    | '/api/public/send-booking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AirportTransfersRoute: typeof AirportTransfersRoute
  AirportsWeServeRoute: typeof AirportsWeServeRoute
  BookOnlineRoute: typeof BookOnlineRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  LongDistanceRoute: typeof LongDistanceRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkiResortRoute: typeof SkiResortRoute
  TermsRoute: typeof TermsRoute
  ApiPublicSendBookingRoute: typeof ApiPublicSendBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ski-resort': {
      id: '/ski-resort'
      path: '/ski-resort'
      fullPath: '/ski-resort'
      preLoaderRoute: typeof SkiResortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-distance': {
      id: '/long-distance'
      path: '/long-distance'
      fullPath: '/long-distance'
      preLoaderRoute: typeof LongDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-online': {
      id: '/book-online'
      path: '/book-online'
      fullPath: '/book-online'
      preLoaderRoute: typeof BookOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports-we-serve': {
      id: '/airports-we-serve'
      path: '/airports-we-serve'
      fullPath: '/airports-we-serve'
      preLoaderRoute: typeof AirportsWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfers': {
      id: '/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof AirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-booking': {
      id: '/api/public/send-booking'
      path: '/api/public/send-booking'
      fullPath: '/api/public/send-booking'
      preLoaderRoute: typeof ApiPublicSendBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AirportTransfersRoute: AirportTransfersRoute,
  AirportsWeServeRoute: AirportsWeServeRoute,
  BookOnlineRoute: BookOnlineRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  LongDistanceRoute: LongDistanceRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkiResortRoute: SkiResortRoute,
  TermsRoute: TermsRoute,
  ApiPublicSendBookingRoute: ApiPublicSendBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
